### ISSUE TITLE
Investigate non-extension based file identification

### ISSUE THREAD

**Issue by paulmillar** [jkotan/scingestor#166]
NB:  This is just sharing an idea.  I am *not* reporting a deficiency in the current approach.

I noticed the recent commit that updates the code (#165)  to identify NeXus files by adding more file extensions (`.h5`, `.ndf`, `.nx`).

I was wondering whether a more flexible approach might be to identify HDF5/NeXus files from their contents, rather than from their file extensions.  Identifying HDF5 files seems already supported; at least, on my laptop:

```
paul@sprocket:~/Downloads$ file alcl3-K-etmd.h5 
alcl3-K-etmd.h5: Hierarchical Data Format (version 5) data
paul@sprocket:~/Downloads$ 
```

Identifying the file as NeXus might be harder.  I know that people at FLASH write HDF5 files that are not NeXus, but I guess on P08 all HDF5 files use NeXus (to some extent), right?

**Comment by jkotan** [comment]
Currently, the ingestor receives only the `scan name` of the dataset. According to this scan name it searches for the master file by adding predefined extensions, firstly for nexus files then for fio files. If the master file is not found the ingestor generates simple  dataset metadata from the beamline metadata file.

So the file extension (with specific order) have to be either hard coded in the code or provided by the user within the scingestor configuration (not implemented yet).

You can have `mytest_12345.nxs`, `mytest_12345.h5` , `mytest_12345.fio` files and scingestor has to decide which one is the master file

**Comment by paulmillar** [comment]
Ah, sorry, I misunderstood what was happening here.

A follow-up question: is the master file written by software under DESY's control?

**Comment by jkotan** [comment]
Yes, the master file is usually created by Sardana (But it could be other user program/script). 
In Sardana for one scan you can create simultaniously many different files (with different FileRecorders) containing more all less the same information but in a different format. Usually in sardana a file format is defined by its file extension.
By default I assume that the master file is NeXus file e.g. `.nxs` but in some cases I can image a user would like to fetch metadata e.g. from a  FIO file.

**Comment by paulmillar** [comment]
Ah, OK.  So in many cases "our" software (Sardana) is writing the files, but there are cases where the data is written by software outside of our control.

Sorry, a couple more stupid questions...

What is a FIO file? 

What is a "master file"?  Is this an HDF5 file with links to all the other HDF5 files?

**Comment by jkotan** [comment]
A FIO File format is a simple data text format, used heavily in DESY designed by Thorsten many year ago.
A master file is a main file which contain metadata and links to detector files (in case of HDF5). 
For SciCat the master file could be a FIO file. The choice is performed by a beamline scientist or a user.

**Comment by paulmillar** [comment]
Thanks for the info.

Is the FIO format documented somewhere?

Also, does FIO support links to other files, like HDF5 does?

**Comment by paulmillar** [comment]
OK, thanks for the answers: that's clear.

One last question: do you have an idea how much data is written using the FIO format?

That's rather a vague questions because I'm not sure how to frame it.  Perhaps a more concrete question would be: how many beamlines use FIO, or how many  files are written are written with FIO, or ...

**Comment by jkotan** [comment]
Which file recorders are used is defined by user groups. 
But I would say almost all beamlines create FIO files e.g. P08 for the current scicat ingestor tests creates both NeXus and FIO, simultaneously.
Creating FIO files is cheap and it is easy to view the content with any text viewer so users often create them.
Maybe beamlines like P06 or P11 are not using the FIO format but I would not bet.

**Comment by paulmillar** [comment]
OK, again, thanks for the info!
