### ISSUE TITLE
improve comparing timestamps by the (re)ingest script

### ISSUE THREAD

**Issue by jkotan** [jkotan/scingestor#34]
Taking timestamps of  ingestion is not accurate enough so during the comparison it would be good  to add some constant time to ensure the dataset or origdatablock is ingested

**Comment by paulmillar** [comment]
Sorry for asking a stupid question ... it looks like the goal here is to support some kind of comparison between timestamps.  If so, then I'm wondering why are we comparing timestamps?

**Comment by jkotan** [comment]
In `scicat-ingested-dataset-{beamtime}.lst` files I store timestamps  when the dataset/origdatablock was ingested, e.g.
```
myscan_00001 1658392262.8381445
myscan_00002 1658392264.4545466
```
For each scan there are *scan.json and *.datablock.json created. 
At the end of the beamtime one can run the reingestion script which checks if timestamps stored in the  `scicat-ingested-dataset-{beamtime}.lst` are not greater than modification times of the above *.json files, i.e. if user modified them to update metadata.
If so I compare metadata and if metadata were changed I reingest them. 
So the timestamps are to save the time in comparing metadata (as a first hint).

In current implementation I was storing the timestamps generated just after the ingestion. 
But it turns out it is not good solution because you can have tiny different in timestamps  i.e. when *.json was modified almost during ingestion. 
In PR I try to introduce time_eps but this approach is wrong so I need to rewrite the PR and store in scicat-ingested-dataset-{beamtime}.lst not timestamps generated by ingestor by timpstamps of *.json modification, i.e. to compare really corresponding values.
