### ISSUE TITLE
adopt tests to newer version of nxstools (>=3.24.0)

### ISSUE THREAD

**Issue by jkotan** [jkotan/scingestor#55]
In  nxstools (>=3.24.0) empty `techniques` were added to metadata if it does not exist. Therefore we need to adopt the scingestor tests to the changes.

**Comment by paulmillar** [comment]
Would it make sense to add some real techniques?

For example, see:

https://docs.google.com/document/d/1UEQERsoIu0oItLi1vhEpAPuNqJBCQ1LgOFnQe65Jahc/edit?usp=sharing

**Comment by jkotan** [comment]
Yes. In nexus files the  techniques are defined by application definitions. So if it is defined I take it from the `NXentry.definition` field.

**Comment by paulmillar** [comment]
Your comment about NXentry.definition could be true for NeXus files (sorry, I don't know enough NeXus to comment), but PaNET is defined independently of NeXus.

PaNET is (supposed to be / will be) the standard way of describing the scientific technique, something that is common across all photon and neutron facilities in Europe, so should allow searching for dataset by technique across all PaN facilities.

In this specific case, you're just updating the existing unit-tests.  Why not add an extra unit-test case with a PaNET term?

The link above contains some examples that could be copy-n-pasted into the unit tests.

Cheers,
Paul.

**Comment by paulmillar** [comment]
Alternatively, adding PaNET unit-tests could be a separate issue, allowing this issue to be closed.

**Comment by jkotan** [comment]
Yes. It is good idea.I to add PaNET techniques to existing test cases. I will do it in this issue. Thanks for hints.
